### PR TITLE
Adds crayon as a dependency to be installed in the docker dev image

### PR DESCRIPTION
**Pull request by poplav**
Fixes https://github.com/IRkernel/IRkernel/issues/399

### CODE REVIEW

**Comment by flying-sheep** [comment]
thanks, but please fix it [here](https://github.com/jupyter/docker-stacks/blob/master/r-notebook/Dockerfile) for everyone!

**Comment by poplav** [comment]
@flying-sheep I feel like it should only be fixed in the docker stacks when the irkernel version is updated.  At the current time the docker stacks serves its purpose as a stable environment.  The docker image here serves its purpose as a dockerized dev environment that should get the bleeding edge updates.  Once the base docker image is updated on the cycle of a new irkernel release I think the fixes here can be removed?  Thoughts?  In essence I am trying to say there is a difference between the stable env in docker stacks and the dev version here.

**Comment by flying-sheep** [comment]
ah, but there isn’t a stable version of IRkernel out yet…

we’re still 0.x, and don’t even have it up on CRAN. but i’ll reopen

**Comment by takluyver** [comment]
Calling projects 0.x doesn't really signify much nowadays, I think. IPython was in '0.x' for over ten years. It doesn't stop people treating the 0.x releases as releases :-)

**Comment by flying-sheep** [comment]
would releasing 0.7 ASAP help :wink:

**Comment by poplav** [comment]
I'll open a PR on docker stacks and close this...this shouldn't be an issue.

**Comment by flying-sheep** [comment]
thanks! i just thought that spreading our dependencies and instructions over too many places, it gets unmaintainable

**Pull request closed without merging**
