### PR TITLE
Update kernel.js

### PR DESCRIPTION
**Pull request by xuestrange**
change pipe input from `%>%` to `|>`

### CODE REVIEW

**Comment by flying-sheep** [comment]
does RStudio do that already?

**Comment by flying-sheep** [comment]
Hi! Why did you close it? I’m just thinking about if that’s already a good idea and enough people are on R 4.1 yet

**Comment by xuestrange** [comment]
> Hi! Why did you close it? I’m just thinking about if that’s already a good idea and enough people are on R 4.1 yet

This PR has been opened for 3 months, I thought it couldn't be merged.

**Comment by flying-sheep** [comment]
I have a lot of things to juggle. So I either deal with something (close merge) or ask for a clarification and wait for the notification that tells me there’s been an answer.

So what do you know about 4.1 adoption: Is it high enough that we can already switch to the new syntax?

**Comment by xuestrange** [comment]
> I have a lot of things to juggle. So I either deal with something (close merge) or ask for a clarification and wait for the notification that tells me there’s been an answer.
> 
> So what do you know about 4.1 adoption: Is it high enough that we can already switch to the new syntax?

I am not sure. None of my classmates write R in jupyter. Rstudio inputs `%>%`  by default unless you turn the option `use |>` on. Maybe better to keep in line with Rstudio.

**Comment by flying-sheep** [comment]
Yup. Maybe we can merge this once RStudio has `|>` by default.

**Pull request closed without merging**
