### PR TITLE
Mark JSON message data as utf-8 before parsing

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-215

### CODE REVIEW

**Comment by takluyver** [comment]
@flying-sheep I ran into another unicode issue while testing this. If R thinks it can't display a character, it escapes it like this: `<U+884C>` (vs Python style `\u884c`). These sequences are being included raw in the HTML repr produces, so the browser tries to interpret them as HTML tags and doesn't show anything. repr should probably be escaping strings for the HTML representation.

**Comment by flying-sheep** [comment]
honestly that’s a jsonlite bug. but no harm in explicitly setting the encoding before they fix their stuff

**Comment by jeroenooms** [comment]
@flying-sheep no it's not. In R each string is marked with an encoding. If you are creating a character vector based on a `const char` in utf8 encoding but you tell R that it should treat it as native encoding, then the bug is on you. Almost all string methods will fail obviously give strange results on this object. 

The `jsonlite` package will try convert strings into utf8, which obviously leads to strange results if you had marked the string incorrectly in the first place.

**Comment by flying-sheep** [comment]
jup, i realized that seconds before you posted :laughing: 

but jsonlite has a bug: `toJSON` doesn’t declare an encoding!

**Comment by takluyver** [comment]
I suspect it's just ambiguous. JSON is defined in terms of characters (well, unicode code points), with a note that the default encoding is utf-8. It looks like R has a single type for strings and bytes, like Python 2, so you can argue either that jsonlite is getting characters and should treat them as whatever characters R thinks they are, or that jsonlite is getting bytes and should treat them as UTF-8.

Either way, there's nothing wrong with this, and it makes stuff work. :-)

**Comment by flying-sheep** [comment]
jup, edited my comment :smile: 

i also DRYed your code in 64d069474f43b9bfdee7d04e58e080a160502972

**Comment by jeroenooms** [comment]
@takluyver  if `jsonlite::fromJSON` would always assume utf8, windows users would get very strange behaviour. For example they could not even copy-paste something like this in the console:

```r
fromJSON('{"food" : "寿司"}')
```

Because the console is native encoding, so `fromJSON` would actually have to treat this string as something else than what is actually displayed? 

Really there is only one proper solution here, you must mark your strings with the correct encoding :-) Once you do, R and jsonlite will automatically convert between encodings when needed.

**Comment by flying-sheep** [comment]
jup, it’s done. as said, i realized that jsonlite does the right thing!

i wish everything could be utf-8 already :angry:

**Comment by takluyver** [comment]
Well, that's actually up to R's Windows interface - AIUI it's possible to read UTF-16 from the Windows console, which could then be translated unambiguously to UTF-8. But most Unix-y programs (including Python, for now, and presumably R too) ignore that, and use the older interfaces that give them bytes in the current 'code page'.

**Pull request merged**
