### PR TITLE
Try installing pbdZMQ on Travis

### PR DESCRIPTION
**Pull request by takluyver**

### CODE REVIEW

**Comment by flying-sheep** [comment]
you should also remove the `r-rzmq` from the `conda install` call

**Comment by takluyver** [comment]
Myeh: `error: ISO C++ 1998 does not support ‘long long’ [-Werror=long-long]`

**Comment by flying-sheep** [comment]
hmm, according to jedisct1/libsodium#104, that won’t be changed, so maybe we can do `-Wno-error=long-long`?

**Comment by takluyver** [comment]
OK, it looks like without needing to install rzmq, we can install a newer zmq and libsodium, and the error goes away :-)

**Comment by flying-sheep** [comment]
ok cool, then i’ll do `withCallingHandlers(..., warning = stop)`

**Pull request merged**
