### PR TITLE
leave the isolating to IRdisplay

### PR DESCRIPTION
**Pull request by flying-sheep**
this will work now, right?

i’ll add a test :smile:

### CODE REVIEW

**Comment by flying-sheep** [comment]
all non-mac stuff green, merging

**Comment by janschulz** [comment]
Where is the test? :-) Otherwise +1

**Comment by flying-sheep** [comment]
lol sorry, will do!

**Comment by flying-sheep** [comment]
done: 2af9a332e16611e9a7cb514684efbb6d19538a7d

**Pull request merged**
