### PR TITLE
Switch to HTTPS on github.io

### PR DESCRIPTION
**Pull request by rgbkrk**
https://irkernel.github.io/ totally works

### CODE REVIEW

**Comment by takluyver** [comment]
Good catch

**Comment by takluyver** [comment]
@JanSchulz do we need to specify the dependencies in `install.packages()`? I'd expect it to use the same repo when installing dependencies, in which case we should just be able to recommend:

```R
install.packages("IRkernel", repos="https://irkernel.github.io/")
```

**Comment by JanSchulz** [comment]
@takluyver AFAIK we don't need dependencies in `install.packages`, but I used them to install everything even if a package with the same version was already installed.

We might also want to switch to drat (see here for a comment: https://github.com/eddelbuettel/drat/pull/16#issuecomment-96288353) , which would get us this:

```
drat::addRepo("irkernel")           # short, sweet, simple -> add to ~/.Rprofile
install.packages("IRkernel")        # assuming the other are Depends
update.packages()                   # no need for any repos argument
```

* + short, kind of an evolving standard
* + adding it to Rprofile gets `update.packages` for free 
* ~ `update.packages` can also be achieved via three lines in  `~/.Rprofile`
* - one more package to install as a user
* - installation without drat will need a slightly different URL (irkernel.github.io/drat)

**Comment by takluyver** [comment]
Let's leave it as is for now - `drat` may pay off later, but for initial installs it's a couple of extra steps. I like that with the current setup a single command can get the packages installed.

**Pull request merged**
