### PR TITLE
http instead of https

### PR DESCRIPTION
**Pull request by randy3k**
as title.

### CODE REVIEW

**Comment by rgbkrk** [comment]
What's preventing you from using https?

**Comment by randy3k** [comment]
I don't know, it just doesn't work

```
> install.packages(c('rzmq','repr','IRkernel','IRdisplay'), repos = 'https://irkernel.github.io/', type = 'source')
Installing packages into ‘/Users/Randy/Library/R/3.2/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://irkernel.github.io/src/contrib
Warning message:
packages ‘rzmq’, ‘repr’, ‘IRkernel’, ‘IRdisplay’ are not available (for R version 3.2.0) 
```

It works if i use http.

**Comment by randy3k** [comment]
The R function `download.file` doesn't support https by default. https://stat.ethz.ch/R-manual/R-devel/library/utils/html/download.file.html

**Comment by rgbkrk** [comment]
Now that's ugly. :unamused: 

I'm so sorry. I have libcurl setup on all my systems, but I know that I'm probably an outlier (Linux or OS X only), since I'm assuming most R users are on Windows. :fallen_leaf:

**Comment by takluyver** [comment]
Just spoken to @jeroenooms about this. Supplying `method='curl'` makes it work if curl is installed. But I imagine it won't be available on Windows (with any reliability). 'libcurl' is a new feature in R 3.2.0 - I'm not sure if it will be there on Windows or not.

It seems like a pretty serious security hole that packages are installed from http by default, but I don't know what else we can do for this.

**Comment by randy3k** [comment]
Perhaps rolling back to the `devtools` approach?

**Comment by takluyver** [comment]
Perhaps, but I'd like to avoid that - it's significantly more steps for
users. Can devtools even install binary packages? If not, it's not really
an option. And if devtools itself has to be installed over http, it's not
really a security benefit.

**Comment by jeroenooms** [comment]
Best to just stick with http for now, like all other packages. This problem will eventually solve itself with better native ssl support in R coming up.

**Comment by randy3k** [comment]
@jeroenooms :+1:

**Comment by rgbkrk** [comment]
Great to hear @jeroenooms! :sweat_smile:

**Comment by takluyver** [comment]
Thanks all

**Comment by rgbkrk** [comment]
Thank you @randy3k, sorry for the trouble.

**Pull request merged**
