### PR TITLE
Added a Dockerfile

### PR DESCRIPTION
**Pull request by benjaminabel**
This is a dockerfile based on <https://github.com/jupyter/notebook/blob/master/Dockerfile>

### CODE REVIEW

**Comment by rgbkrk** [comment]
Seems alright to me.

**Comment by takluyver** [comment]
Is there anywhere else it would make sense to maintain this? We'll make it work if this is the best place, but I don't know much about Docker, so I'd rather it lived somewhere under the eye of people like @rgbkrk .

**Comment by JanSchulz** [comment]
"jupyter-contrib/docker-recipes" ?

**Comment by benjaminabel** [comment]
I think the IRkernel repo is the place where it should live, first for the visibility and second because the Dockerfile may need to change as the IRkernel change. It don't add too much maintenance, just need to repercut installations steps changes for ubuntu in the Dockerfile. I can help in that maintenance. Of course I can remove my name as a MAINTAINER in the `Dockerfile`

**Comment by benjaminabel** [comment]
You can get more visibility on the `Dockerfile` usability using travis, I created a branch adding a travis build [here](https://github.com/benjaminabel/IRkernel/tree/dockerfile). like this you can track if the Dockefile ist broken however the build time is quite long <https://travis-ci.org/benjaminabel/IRkernel>

**Comment by benjaminabel** [comment]
I close the PR and created a [gist](https://gist.github.com/benjaminabel/7986fd5647340e91778f) for those you are intersted.

**Comment by takluyver** [comment]
Sorry, I had just forgotten about it - it doesn't sound like anyone knows of a better place for it to live, so I'm happy to have it here. So long as you don't mind us pinging you if people report bugs about it ;-).

**Comment by benjaminabel** [comment]
@takluyver I cleaned up the Dockefile, inheriting some more commands from the official jupyter notebook Dockefile, updated the README and rebased. It's ready to merge.

**Comment by benjaminabel** [comment]
Of course I can help maintaining it.

**Comment by takluyver** [comment]
Thanks!

**Pull request merged**
