### PR TITLE
bind last output to .Last.value

### LINKED ISSUE #405: .Last.value does not work in IRkernel
I guess the reason `.Last.value` doesn't work in IRkernel is exactly the same reason why it doesn't work in `knitr`: http://stackoverflow.com/questions/31475226/using-last-value-in-rmarkdown-knitr

With the understanding that it doesn't work, I do find that it is quite handy to have the last output stored so that it could be used later, it is particularly helpful when using the autograde feature of [nbgrader](https://github.com/jupyter/nbgrader).

Does it make sense and is it difficult to enable `.Last.value`?

### PR DESCRIPTION
**Pull request by randy3k**
close #405 

Thanks @flying-sheep for pointing out the relevant code. Now `.Last.value` works as expected (even within a cell).

screen shot 2016-09-11 at 12 27 43 am

### CODE REVIEW

**Comment by randy3k** [comment]
I think the test failure is not relevant, but there is a note

```
Found the following possibly unsafe calls:
File ‘IRkernel/R/utils.r’:
  unlockBinding(".Last.value", .BaseNamespaceEnv)
```

Basically, it says unlocking `.Last.value` is not safe, but I don't know there is a way to do it safely. Perhaps assigning the last value to sth like `.jupyter.last_value`?

**Comment by randy3k** [comment]
I just note that the behaviour is different from R console.

```
> x <- 1
> x
[1] 1
> .Last.value
[1] 1
> x <- 2
> .Last.value
[1] 2
```

screen shot 2016-09-10 at 4 31 46 pm

It is because `x <- 2` has no output...

**Comment by flying-sheep** [comment]
well, [the docs say that it lives in the base namespace](http://www.rdocumentation.org/packages/base/versions/3.3.1/topics/Last.value), so you’re doing the right thing.

we’re basically replacing the frontend of the whole R runtime, so it’s expected that we do a few things that are considered “unsafe”.

and [of course your changes cause the test failure](https://travis-ci.org/IRkernel/IRkernel/jobs/159067956#L904): we just test for the number of lines the “NOTE” has… we could do this better, but for now we have to update and account for every single line. as you can see it went from 4→9. what lines gets added?

**Comment by randy3k** [comment]
I have updated the tests, 6 out of 8 of the jobs pass except the devel versions on linux. I have no clues how to fix them..

**Comment by flying-sheep** [comment]
it’s not “8 lines from the ‘attach’ NOTE”, though. it’s still 4 for that one and 4 for your new one.

**Comment by randy3k** [comment]
I fixed the comments in `.travis.sh`

**Comment by flying-sheep** [comment]
great. i’ll wait for the test results and merge

**Comment by flying-sheep** [comment]
oh, and of course: thank you :smile:

**Comment by randy3k** [comment]
😀
You are welcome

**Pull request merged**
