### PR TITLE
Message protocol 5 doesn't use 'source' field

### PR DESCRIPTION
**Pull request by takluyver**
http://jupyter-client.readthedocs.io/en/latest/messaging.html#display-data

### CODE REVIEW

**Comment by flying-sheep** [comment]
Yeah, they’ve been failing for some time, but I have no idea why.

Could you please add a test for protocol validity? (or enable checking this in jupyter-kernel-tests, as i assume it should be in there)?

**Comment by takluyver** [comment]
It looks like JKT doesn't currently support checking for unexpected extra attributes. I'll work on that, but it's not a five minute job to do it right.

Are you happy if I comment out the Mac tests and open an issue for someone to look at them later? They're slower than the Linux tests, and CI is less useful if we're used to it failing.

**Comment by flying-sheep** [comment]
yes, very happy, i wanted to do that long ago. no idea why i didn’t…

**Comment by kojix2** [comment]
Thank you @takluyver @flying-sheep

**Pull request merged**
