### PR TITLE
Fix passing pager text data to page() function

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-422

### CODE REVIEW

**Comment by flying-sheep** [comment]
hmm, this test failure seems spurious: https://travis-ci.org/IRkernel/IRkernel/jobs/176129298

**Comment by takluyver** [comment]
Agreed, have restarted that job

**Comment by takluyver** [comment]
OK, eventually the build has completed. Travis is taking its time today...

**Comment by flying-sheep** [comment]
OK, great!

**Pull request merged**
