### PR TITLE
Add busy/idle around all shell replies

### PR DESCRIPTION
**Pull request by parente**
For #311

This is done totally by eyeballing it so far. I need to get
a dev environment setup to test it.

I see a test target in the Makefile but I don't see where
tests are defined. I wouldn't be surprised if I'm missing them.
(I'm very much an R newbie.)

### CODE REVIEW

**Comment by takluyver** [comment]
I think we could do it in `handle_shell()`, so the code is only needed in one place. Unless I'm missing something.

**Comment by parente** [comment]
If we do it wholesale in `handle_shell`, it slightly changes the order of messages for `execute_request` because now the idle status will come after the `execute_reply` instead of before it like it does now.

Also, unless a special check is added to `handle_shell` for the shutdown case, and busy status message will be sent, but an idle will mostly likely not since there's a quit in the shutdown method. It's probably not a big deal, but perhaps that will leave some UIs in a weird state?

I'm totally willing to switch to doing it in one place. Just let me know if either of the above is a real issue or not.

**Comment by takluyver** [comment]
> If we do it wholesale in handle_shell, it slightly changes the order of messages for execute_request because now the idle status will come after the execute_reply instead of before it like it does now.

They go on different channels, so the order isn't reliable anyway. :-)

> Also, unless a special check is added to handle_shell for the shutdown case, and busy status message will be sent, but an idle will mostly likely not since there's a quit in the shutdown method. It's probably not a big deal, but perhaps that will leave some UIs in a weird state?

Good point. What do other kernels do with status on shutdown_request?

**Comment by parente** [comment]
> They go on different channels, so the order isn't reliable anyway. :-)

Ah, right. I was dwelling on the websocket where it's all serialized to one stream and should have been thinking about zmq.

> Good point. What do other kernels do with status on shutdown_request?

ipykernel sends busy/idle around shutdown and all other messages (https://github.com/ipython/ipykernel/blob/bc4fe8916abb28519adc9214abdb088afa14c323/ipykernel/kernelbase.py#L206). And it leads to the stuck indicator in notebook. :)

screen shot 2016-05-05 at 9 37 18 am

That said, I'm convinced we should replicate what ipykernel is doing and just wrap busy/idle around everything in one place. I'll update the PR.

**Comment by parente** [comment]
Should be good to go.

**Comment by takluyver** [comment]
Thanks @parente

**Pull request merged**
