### PR TITLE
Isolate plot SVGs to avoid clashes with the page

### PR DESCRIPTION
**Pull request by takluyver**
This improves SVG plots for me, and I hope it will fix a number of plotting bugs like #117 and #125.

### CODE REVIEW

**Comment by randy3k** [comment]
It does solve #117 , but the images are not shown correctly
screen shot 2015-05-08 at 11 39 06 pm

**Comment by flying-sheep** [comment]
[here](https://github.com/jupyter/notebook/blob/cc54d7d63fe4fd375a89409f4a3ce9cf888451ad/jupyter_notebook/static/notebook/js/outputarea.js#L352-L379) is the relevant code.

i’ll look at what goes wrong.

**Comment by randy3k** [comment]
I just realized that it works on ipython 3.0, but not the dev branch of juypter notebook..

**Comment by flying-sheep** [comment]
hmm, report a bug there?

**Pull request merged**
