### PR TITLE
Move rich display option

### PR DESCRIPTION
**Pull request by janschulz**
IRdisplay used to set this option and now stopped using it (see https://github.com/IRkernel/IRdisplay/pull/31). Actually this option is more a "auto rich display" option, not "use rich display at all", so it fits much better in the kernel itself.
    
See https://github.com/IRkernel/IRdisplay/issues/28 for the discussion

### CODE REVIEW

**Comment by janschulz** [comment]
The linux tests are green, as are my local windows based tests and CHECK

The mac tests seem to run into a timeout? :-( I've restarted the travis run, maybe this time it is better, but I guess the build will take ages if the mac builds get "activated" but then do not run -> 4 stale builds on mac and the last linux one is waiting to get activated :-(

**Comment by janschulz** [comment]
Update: right now all 5 mac builds are not running and the linux based test runs are green -> IMO if nothing else is missing in this PR, this is IMO good to merge. https://travis-ci.org/IRkernel/IRkernel/builds/140894616

**Comment by janschulz** [comment]
Update: and the first two mac builds succeeded, but the rest is stalled again :-(

**Comment by janschulz** [comment]
WTF: https://travis-ci.org/IRkernel/IRkernel/jobs/140894628

this is happening on oldrel:
```
$ Rscript -e 'devtools::install_github(c("IRkernel/IRdisplay"), build_vignettes = FALSE)'
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/travis/R/Library/digest/libs/digest.so':
  dlopen(/Users/travis/R/Library/digest/libs/digest.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.3/Resources/lib/libR.dylib
  Referenced from: /Users/travis/R/Library/digest/libs/digest.so
  Reason: Incompatible library version: digest.so requires version 3.3.0 or later, but libR.dylib provides version 3.2.0
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

Is that a broken R installation or travis environment?

CC:  @craigcitro @jimhester

**Comment by janschulz** [comment]
On r devel, it breaks with:

```
 curl -Lo /tmp/R.pkg https://cloud.r-project.org/bin/macosx/old/R-devel.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0    647      0 --:--:-- --:--:-- --:--:--   647
Installing OS X binary package for R
0.00s$ sudo installer -pkg "/tmp/R.pkg" -target /
installer: Error the package path specified was invalid: '/tmp/R.pkg'.
The command "sudo installer -pkg "/tmp/R.pkg" -target /" failed and exited with 1 during .
```

**Comment by flying-sheep** [comment]
that’s at least more helpful than everything breaking!

**Pull request merged**
